name: EventsMania
main: gg.aquatic.eventsmania.EventsMania
version: ${version}
api-version: 1.21

dependencies:
  server:
    Waves:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
    Nexo:
      load: BEFORE
      required: false
    CraftEngine:
      load: BEFORE
      required: false